# Generated by Django 4.0.4 on 2022-05-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_police_uniquepolice_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Police',
            new_name='PoliceOfficer',
        ),
    ]
