# Generated by Django 4.0.4 on 2022-05-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_police_policeofficer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeofficer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='policeofficer',
            name='password',
        ),
    ]
