# Generated by Django 4.0.4 on 2022-05-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_policeofficer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='uniquepolice_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
