# Generated by Django 4.0.4 on 2022-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_policeofficer_uniquepolice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='uniquepolice_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
