# Generated by Django 4.0.4 on 2022-05-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_citizen_citizendetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('criminalid', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('birthdate', models.DateField()),
                ('residence', models.CharField(default='', max_length=1000)),
                ('arrestplace', models.CharField(default='', max_length=100)),
                ('crime', models.CharField(default='', max_length=10000)),
                ('arrestdate', models.DateField()),
                ('inspectorincharge', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default='', upload_to='login/criminals/images')),
            ],
        ),
    ]
