# Generated by Django 4.0.4 on 2022-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_criminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contactperson', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='', upload_to='login/missing/images')),
            ],
        ),
    ]
