# Generated by Django 4.0.4 on 2022-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_missing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('residence', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=10000)),
                ('picture1', models.ImageField(default='', upload_to='login/criminals/images')),
                ('picture2', models.ImageField(default='', upload_to='login/criminals/images')),
                ('picture3', models.ImageField(default='', upload_to='login/criminals/images')),
                ('picture4', models.ImageField(default='', upload_to='login/criminals/images')),
                ('picture5', models.ImageField(default='', upload_to='login/criminals/images')),
            ],
        ),
    ]
