# Generated by Django 4.0.4 on 2022-05-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='picture1',
            field=models.ImageField(default='', upload_to='login/report/images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='picture2',
            field=models.ImageField(default='', upload_to='login/report/images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='picture3',
            field=models.ImageField(default='', upload_to='login/report/images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='picture4',
            field=models.ImageField(default='', upload_to='login/report/images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='picture5',
            field=models.ImageField(default='', upload_to='login/report/images'),
        ),
    ]
