# Generated by Django 4.0.4 on 2022-05-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_report_picture1_alter_report_picture2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
