# Generated by Django 4.0.4 on 2022-05-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
