# Generated by Django 4.0.4 on 2022-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('residence', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=10000)),
                ('picture1', models.ImageField(blank=True, default='', upload_to='login/report/images')),
                ('picture2', models.ImageField(blank=True, default='', upload_to='login/report/images')),
                ('picture3', models.ImageField(blank=True, default='', upload_to='login/report/images')),
                ('picture4', models.ImageField(blank=True, default='', upload_to='login/report/images')),
                ('picture5', models.ImageField(blank=True, default='', upload_to='login/report/images')),
            ],
        ),
    ]
