# Generated by Django 4.0.4 on 2022-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_id', models.IntegerField(default=0)),
                ('update_desc', models.CharField(max_length=6000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
