# Generated by Django 4.0.4 on 2022-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_reportupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('criminalid', models.IntegerField(default=0)),
                ('update_crime', models.CharField(max_length=6000)),
                ('update_locations', models.CharField(max_length=6000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
