# Generated by Django 4.0.4 on 2022-05-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_missing_foundby_missing_foundpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='foundby',
            field=models.CharField(default='', max_length=100),
        ),
    ]
