# Generated by Django 4.0.4 on 2022-05-22 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_missing_foundby'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalupdate',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
