# Generated by Django 4.0.4 on 2022-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_criminalupdate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalupdate',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
