# Generated by Django 4.0.4 on 2022-05-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_criminalupdate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='arrestdate',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='arrestplace',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='height',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='inspectorincharge',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='weight',
        ),
    ]
