# Generated by Django 4.0.4 on 2022-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_remove_criminal_arrestdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceDetail',
            fields=[
                ('police_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(default='', upload_to='login/police/images')),
            ],
        ),
    ]
