# Generated by Django 4.0.4 on 2022-05-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_policedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='picture4',
        ),
        migrations.RemoveField(
            model_name='report',
            name='picture5',
        ),
        migrations.AddField(
            model_name='report',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='login/report/videos'),
        ),
    ]
