# Generated by Django 4.0.4 on 2022-05-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_remove_report_picture4_remove_report_picture5_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='CitizenDetail',
        ),
        migrations.DeleteModel(
            name='PoliceOfficer',
        ),
        migrations.DeleteModel(
            name='PoliceOfficerDetail',
        ),
    ]
