# Generated by Django 4.0.4 on 2022-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_delete_citizen_delete_citizendetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalupdate',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='criminalupdate',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
